### Testing getAll syllabus
GET http://localhost:1996/api/syllabus

### Testing getOne syllabus
GET http://localhost:1996/api/syllabus/CC751

### Testing getSome syllabus
POST http://localhost:1996/api/syllabus
Content-Type: application/json

{
  "args": {
    "ids": ["CC004", "CC008", "CC010"]
  }
}

### Testing selectCourses
PATCH http://localhost:1996/api//user/selectCourses
Content-Type: application/json

{
  "args": {
    "id": "fW5bcQXoPKU8c1HkQEjd24dUyh62",
    "selectedCourses": ["CC004", "CC008", "CC010"]
  }
}

### Testing store a user
POST http://localhost:1996/api/users
Content-Type: application/json

{
  "args": {
    "id": "NkXvRnfkpeUIlT7GQdZg5hls1Qf1",
    "lastName": "Vera",
    "name": "Bryan"
  }
}

### Testing get one user
GET http://localhost:1996/api/user/fW5bcQXoPKU8c1HkQEjd24dUyh62

### Testing SCE
POST http://localhost:1996/api/search
Content-Type: application/json

{
  "args": {
    "query": "java",
    "keyWord": "tutorial"
  }
}
